### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by psydvl** [flathub/org.telegram.desktop.webview#10]
How can I use this add-on with telegram?
Should I activate it somehow?
Also, how to use it with beta version?

**Comment by ilya-fedin** [comment]
It should automatically install with the stable version. With the beta version you just need to install it.

**Comment by psydvl** [comment]
1) Is it using for bot's web apps only or for Instant View somehow too?
2) Am I miss something, or it's not used for Wayland neither GNOME (mutter display server)?

**Comment by ilya-fedin** [comment]
1. Telegram Desktop doesn't have Instant View
2. It's bugged on mutter with X for some reason, so it's disabled. I don't know how to implement it on Wayland, I tried to contact some Wayland developers, they all say that window embedding on Wayland impossible and they don't want to add it... They suggested implementing nested compositor, but I don't want to implement entire compositor just for this, it just doesn't worth the effort.

**Comment by psydvl** [comment]
Thank you
